# Generated by Django 4.2.6 on 2024-01-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identification',
            field=models.CharField(default='0', max_length=5, unique=True),
        ),
    ]
