# Generated by Django 4.2.6 on 2024-02-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='BS_Bullets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='BS_E_BoatsDestroyed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='BS_E_Hit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='BS_E_Miss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='BS_GameCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='BS_P_BoatsDestroyed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='BS_P_Hit',
            field=models.IntegerField(default=0),
        ),
    ]
