# Generated by Django 4.2.6 on 2024-01-10 09:30

import chatApp.enumChat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connexionStatus',
            field=models.IntegerField(default=chatApp.enumChat.connexionStatus['Disconnected']),
        ),
    ]
