# Generated by Django 4.2.6 on 2024-02-05 10:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_user_bs_bullets_user_bs_e_boatsdestroyed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Friends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
    ]
