# Generated by Django 4.2.6 on 2024-01-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_user_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identification',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
