# Generated by Django 4.2.6 on 2024-02-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_user_bs_bullets_user_bs_e_boatsdestroyed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='BS_G_Lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='BS_G_Win',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='Pong_BallHit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='Pong_Game',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='Pong_Lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='Pong_Point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='Pong_PointTaken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='Pong_Win',
            field=models.IntegerField(default=0),
        ),
    ]
