# Generated by Django 4.2.6 on 2024-02-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_user_bs_g_lose_user_bs_g_win_user_pong_ballhit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Pong_BallHitByOpponent',
            field=models.IntegerField(default=0),
        ),
    ]
