# Generated by Django 4.2.6 on 2024-01-11 09:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_user_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blockedUser',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
    ]
