# Generated by Django 4.2.6 on 2024-02-05 10:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='PendingInvite',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
    ]
