# Generated by Django 4.2.6 on 2024-02-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_user_pong_ballhitbyopponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Pong_Versus_AI',
            field=models.IntegerField(default=0),
        ),
    ]
