# Generated by Django 4.2.6 on 2024-01-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_user_allprivatetalks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identification',
            field=models.CharField(default='NULL'),
        ),
    ]
