# Generated by Django 4.2.6 on 2024-01-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0008_alter_user_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatarImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
