# Generated by Django 4.2.6 on 2024-01-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0009_user_avatarimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatarImage',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
