# Generated by Django 4.2.6 on 2024-01-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0012_alter_user_avatarimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatarImage',
            field=models.BinaryField(blank=True, default=None),
        ),
    ]
