# Generated by Django 4.2.6 on 2024-01-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0014_alter_user_avatarimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customUsername',
            field=models.CharField(default='None'),
        ),
    ]
