# Generated by Django 4.2.6 on 2024-01-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0017_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identification',
        ),
    ]
