# Generated by Django 4.2.6 on 2024-01-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0018_remove_user_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tfEnable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tfType',
            field=models.IntegerField(default=-1),
        ),
    ]
