# Generated by Django 4.2.6 on 2024-01-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0018_remove_user_identification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='customUsername',
            new_name='nickname',
        ),
    ]
