# Generated by Django 4.2.6 on 2024-01-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0019_user_tfenable_user_tftype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tfValidated',
            field=models.BooleanField(default=False),
        ),
    ]
