# Generated by Django 4.2.6 on 2024-01-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0020_user_tfvalidated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tfEnable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tfValidated',
            field=models.BooleanField(default=True),
        ),
    ]
