# Generated by Django 4.2.6 on 2024-01-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0021_alter_user_tfenable_alter_user_tfvalidated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tfEnable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='tfValidated',
            field=models.BooleanField(default=False),
        ),
    ]
