# Generated by Django 4.2.6 on 2024-01-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0022_alter_user_tfenable_alter_user_tfvalidated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tfKey',
            field=models.CharField(blank=True, default=None),
        ),
    ]
