# Generated by Django 4.2.6 on 2024-01-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0023_user_tfkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tfKey',
            field=models.CharField(default=None, null=True),
        ),
    ]
