# Generated by Django 4.2.6 on 2024-01-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0024_alter_user_tfkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tfIsLoggin',
            field=models.BooleanField(default=False),
        ),
    ]
