version: '3'

services:
  nginx:
    build: modules/nginx/
    container_name: container_nginx
    image: image_nginx
    networks:
      - transcendence_network
    volumes:
      - blockchain:/var/blockchain
    restart: on-failure
    ports:
      - "8080:80"
      - "8545"

  #django:
  #  build: modules/django
  #  container_name: containerDjango
  #  image: imageDjango
  #  networks:
  #    - transcendence_network
  #  restart: on-failure
  #  ports:
  #    - "8080:80"

  ganache:
    build: modules/blockchain/ganache
    container_name: container_ganache
    image: image_ganache
    env_file:
      - .env
    networks:
      - transcendence_network
    volumes:
      - blockchain:/var/blockchain
    restart: on-failure
    expose:
      - "8545"

  contract_deployement:
    build: modules/blockchain/contract_deployement
    container_name: container_contract_deployement
    image: image_contract_deployement
    env_file:
      - .env
    networks:
      - transcendence_network
    volumes:
      - blockchain:/var/blockchain
    restart: on-failure
    depends_on:
      - ganache
    expose:
      - "8545"

volumes:
  blockchain:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/data/blockchain'

networks:
  transcendence_network:
    driver: bridge
