version: '3'

services:
  nginx:
    build: srcs/nginx/
    container_name: container_nginx
    image: image_nginx
    networks:
      - transcendence_network
    volumes:
      - blockchain:/var/blockchain
    restart: on-failure
    ports:
      - "8080:80"

  #django:
  #  build: srcs/django
  #  container_name: containerDjango
  #  image: imageDjango
  #  networks:
  #    - transcendence_network
  #  restart: on-failure
  #  ports:
  #    - "8080:80"

  blockchain_node:
    build: srcs/blockchain_node
    container_name: container_blockchain_node
    image: image_blockchain_node
    env_file:
      - .env
    networks:
      - transcendence_network
    volumes:
      - blockchain:/var/blockchain
    restart: on-failure
    expose:
      - "8545"

  blockchain_contract:
    build: srcs/blockchain_contract
    container_name: container_blockchain_contract
    image: image_blockchain_contract
    env_file:
      - .env
    networks:
      - transcendence_network
    volumes:
      - blockchain:/var/blockchain
    restart: on-failure
    depends_on:
      - blockchain_node

  #test_contract:
  #  build: srcs/test_contract
  #  container_name: container_test_contract
  #  image: image_test_contract
  #  env_file:
  #    - .env
  #  networks:
  #    - transcendence_network
  #  volumes:
  #    - blockchain:/var/blockchain
  #  restart: on-failure
  #  depends_on:
  #    - blockchain_contract

volumes:
  blockchain:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/fle-tolg/data/blockchain'

networks:
  transcendence_network:
    driver: bridge
