# Generated by Django 4.2.6 on 2024-02-01 10:37

import chatApp.enumChat
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelName', models.CharField(default='0')),
                ('admin', models.CharField(default='0')),
                ('users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None)),
                ('privacyStatus', models.IntegerField(default=chatApp.enumChat.channelPrivacy['Public'])),
                ('password', models.CharField(blank=True)),
                ('description', models.CharField(default='PAS2DESCRIPTION', max_length=255)),
                ('timeCreation', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P', 'Private Message'), ('C', 'Channel Message')], default='P', max_length=1)),
                ('message', models.CharField(default='NULL')),
                ('sender', models.CharField(default='NULL')),
                ('receiver', models.CharField(default='NULL')),
                ('timeCreation', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
