# Generated by Django 4.2.6 on 2024-01-10 13:46

import chatApp.enumChat
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelName', models.CharField(default='PAS2NOM')),
                ('admin', models.CharField(default='PAS2ADMIN')),
                ('users', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None)),
                ('privacyStatus', models.IntegerField(default=chatApp.enumChat.channelPrivacy['Public'])),
                ('description', models.CharField(default='None', max_length=255)),
                ('timeCreation', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
