# Generated by Django 4.2.6 on 2024-02-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmodels',
            name='channelPicture',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
