# Generated by Django 4.2.6 on 2024-01-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0002_alter_channelmodels_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmodels',
            name='admin',
            field=models.CharField(default='0'),
        ),
        migrations.AlterField(
            model_name='channelmodels',
            name='channelName',
            field=models.CharField(default='0'),
        ),
    ]
