# Generated by Django 4.2.6 on 2024-02-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0002_channelmodels_channelpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodels',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
