# Generated by Django 4.2.6 on 2024-01-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0003_alter_channelmodels_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmodels',
            name='description',
            field=models.CharField(default='PAS2DESCRIPTION', max_length=255),
        ),
    ]
