# Generated by Django 4.2.6 on 2024-02-06 11:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0003_messagemodels_isread'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodels',
            name='readBy',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
    ]
