# Generated by Django 4.2.6 on 2024-01-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0004_alter_channelmodels_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodels',
            name='message',
            field=models.CharField(default='NULL'),
        ),
        migrations.AddField(
            model_name='messagemodels',
            name='receiver',
            field=models.CharField(default='NULL'),
        ),
        migrations.AddField(
            model_name='messagemodels',
            name='sender',
            field=models.CharField(default='NULL'),
        ),
        migrations.AddField(
            model_name='messagemodels',
            name='timeCreation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
