# Generated by Django 4.2.6 on 2024-01-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0005_messagemodels_message_messagemodels_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmodels',
            name='password',
            field=models.CharField(blank=True),
        ),
    ]
