# Generated by Django 4.2.6 on 2024-01-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0006_channelmodels_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodels',
            name='type',
            field=models.CharField(choices=[('P', 'Private Message'), ('C', 'Channel Message')], default='P', max_length=1),
        ),
    ]
