# Generated by Django 4.2.6 on 2023-12-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pongGame', '0004_ponggamemodels_number_ball_touch_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponggamemodels',
            name='reason',
            field=models.CharField(default='AAAAAAAAAHHHHHHHHHHHHHHH', max_length=255),
        ),
    ]
