# Generated by Django 4.2.6 on 2023-12-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentsmodels',
            name='numberOfPlayer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tournamentsmodels',
            name='tournamentsName',
            field=models.CharField(max_length=16),
        ),
    ]
