# Generated by Django 4.2.6 on 2023-12-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentsApp', '0002_alter_tournamentsmodels_numberofplayer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentsmodels',
            old_name='numberOfPlayer',
            new_name='numberOfPlayers',
        ),
        migrations.AddField(
            model_name='tournamentsmodels',
            name='playersId',
            field=models.TextField(null=True),
        ),
    ]
