# Generated by Django 4.2.6 on 2023-12-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentsApp', '0003_rename_numberofplayer_tournamentsmodels_numberofplayers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentsmodels',
            name='creationTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tournamentsmodels',
            name='creatorId',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AddField(
            model_name='tournamentsmodels',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AddField(
            model_name='tournamentsmodels',
            name='privateGame',
            field=models.BooleanField(default=False),
        ),
    ]
