# Generated by Django 4.2.6 on 2023-12-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentsApp', '0007_alter_tournamentsmodels_creatorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentsmodels',
            name='tournamentsType',
            field=models.CharField(default='PONG', max_length=16),
        ),
        migrations.AlterField(
            model_name='tournamentsmodels',
            name='playersId',
            field=models.TextField(default='', null=True),
        ),
    ]
