# Generated by Django 4.2.6 on 2024-01-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentsApp', '0008_tournamentsmodels_tournamentstype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentsmodels',
            name='winner',
            field=models.CharField(default='gpasquet'),
        ),
    ]
