# Generated by Django 4.2.6 on 2024-01-15 13:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentsApp', '0011_alter_tournamentsmodels_playersid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentsmodels',
            name='playersId',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, null=True, size=None),
        ),
    ]
