# Generated by Django 4.2.6 on 2023-12-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PongGameModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=255)),
                ('player2', models.CharField(max_length=255)),
                ('score_player1', models.IntegerField(default=0)),
                ('score_player2', models.IntegerField(default=0)),
                ('number_ball_touch_player1', models.IntegerField(default=0)),
                ('number_ball_touch_player2', models.IntegerField(default=0)),
                ('winner', models.CharField(max_length=255)),
                ('reason', models.CharField(default='gros caca', max_length=255)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
