# Generated by Django 4.2.6 on 2023-12-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pongGameApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponggamemodels',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='ponggamemodels',
            name='player2',
        ),
    ]
