# Generated by Django 4.2.6 on 2023-12-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pongGameApp', '0002_remove_ponggamemodels_player1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponggamemodels',
            name='winner',
        ),
    ]
