# Generated by Django 4.2.6 on 2024-01-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pongGameApp', '0003_remove_ponggamemodels_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponggamemodels',
            name='player1',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='ponggamemodels',
            name='player2',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='ponggamemodels',
            name='winner',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
