# Generated by Django 4.2.6 on 2024-01-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pongGameApp', '0006_remove_ponggamemodels_typegame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponggamemodels',
            name='tournamentId',
            field=models.CharField(default='-1', max_length=255),
        ),
    ]
