# Generated by Django 4.2.6 on 2023-12-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PongGameClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=255)),
                ('player2', models.CharField(max_length=255)),
                ('score_player1', models.IntegerField()),
                ('score_player2', models.IntegerField()),
                ('winner', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
