# Generated by Django 4.2.6 on 2023-12-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pongGame', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponggamemodels',
            name='number_ball_touch_player1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ponggamemodels',
            name='number_ball_touch_player2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ponggamemodels',
            name='score_player1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ponggamemodels',
            name='score_player2',
            field=models.IntegerField(default=0),
        ),
    ]
