# Generated by Django 4.2.6 on 2023-12-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pongGame', '0005_ponggamemodels_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponggamemodels',
            name='reason',
            field=models.CharField(default='gros caca', max_length=255),
        ),
    ]
