# Generated by Django 4.2.6 on 2024-01-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattleshipGameModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(default='None', max_length=255)),
                ('player2', models.CharField(default='None', max_length=255)),
                ('winner', models.CharField(default='None', max_length=255)),
                ('tournamentId', models.CharField(default='-1', max_length=255)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
