# Generated by Django 4.2.6 on 2024-01-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleshipApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleshipgamemodels',
            name='player1_hit',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='battleshipgamemodels',
            name='player2_hit',
            field=models.IntegerField(default=-1),
        ),
    ]
